export const COMMUNITY_LIST_REQUEST = 'COMMUNITY_LIST_REQUEST'
export const COMMUNITY_LIST_SUCCESS = 'COMMUNITY_LIST_SUCCESS'
export const COMMUNITY_LIST_FAIL = 'COMMUNITY_LIST_FAIL'

export const COMMUNITY_CREATE_REQUEST = 'COMMUNITY_CREATE_REQUEST'
export const COMMUNITY_CREATE_SUCCESS = 'COMMUNITY_CREATE_SUCCESS'
export const COMMUNITY_CREATE_FAIL = 'COMMUNITY_CREATE_FAIL'

export const COMMUNITY_DETAILS_REQUEST = 'COMMUNITY_DETAILS_REQUEST'
export const COMMUNITY_DETAILS_SUCCESS = 'COMMUNITY_DETAILS_SUCCESS'
export const COMMUNITY_DETAILS_FAIL = 'COMMUNITY_DETAILS_FAIL'

export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST'
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS'
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL'

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST'
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS'
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL'

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST'
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS'
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL'

export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST'
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS'
export const COMMENT_CREATE_FAIL = 'COMMENT_CREATE_FAIL'

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST'
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS'
export const COMMENT_DELETE_FAIL = 'COMMENT_DELETE_FAIL'

export const POST_LIKE_REQUEST = 'POST_LIKE_REQUEST'
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS'
export const POST_LIKE_FAIL = 'POST_LIKE_FAIL'